title: "Shivam's Tech Blog"
description: "Infra monitoring, automation & DevOps tutorials"
url: "https://<your-github-username>.github.io"  # Replace with your GitHub username
baseurl: ""  # Leave blank unless your site is in a subdirectory

author:
  name: "Shivam Shukla"
  bio: "Engineer | Monitoring & Automation | 14+ years"

theme: minimal-mistakes-jekyll

plugins:
  - jekyll-include-cache

include:
  - _pages
  
logo: "/assets/images/logo.png"
favicon: "/assets/images/favicon.ico"

# Enable custom CSS from assets/css/main.scss
defaults:
  - scope:
      path: ""
    values:
      css: "/assets/css/main.css"  # Custom stylesheet
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
  - scope:
      path: "_pages"
    values:
      layout: single
      author_profile: true

# Optional: show reading time, breadcrumbs, etc.
# You can uncomment and customize these if needed
# reading_time: true
# breadcrumbs: true

# Optional: Social links (customize if desired)
# social:
#   links:
#     - https://github.com/your-username
#     - https://linkedin.com/in/your-profile
